[project]
name = "reddington"
version = "0.1.0"
description = "OSINT based lookup command line tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "requests>=2.32.3",
    "rich>=14.0.0",
]

[project.scripts]
reddington = "src.cli:main"
